# Numpy - Tutorials:

> - Numpy : Numerical Python <br>
> -  NumPy is the fundamental package for scientific computing in Python. <br>
> - It is a Python library that provides a multidimensional array object. 

## 1. Import package

In [3]:
import numpy as np

## 2.Creating Numpy array:

###### np.arange()

In [25]:
#np.arange() --> will be useful, when we know start, end, step size. But dont know howmany values will come

#Method-1: using np.arange()
print("2A. Numpy Array using arange()")

a = np.arange(10)
print(a)
type(a)

2A. Numpy Array using arange()
[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

In [20]:
#Method-2 by providing start, end

b =np.arange(0,10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
#Method-3 by providing start,end,step

c =np.arange(0,10,2)
print(c)

[0 2 4 6 8]


In [26]:
#Try for floating numbers,
a = np.arange(0.1, 8.4, 0.7)
a

array([0.1, 0.8, 1.5, 2.2, 2.9, 3.6, 4.3, 5. , 5.7, 6.4, 7.1, 7.8])

` Hello `