# Numpy - Tutorials:

> - Numpy : Numerical Python <br>
> -  NumPy is the fundamental package for scientific computing in Python. <br>
> - It is a Python library that provides a multidimensional array object. 

# 1. Import package

In [2]:
import numpy as np

# 2.Creating Numpy array:

#### 2A) np.arange()

In [34]:
#arange([start,] stop[, step], [, dtype=None]
#np.arange() --> will be useful, when we know start, end, step size. But dont know howmany #of values will come

#Method-1: using np.arange()
print("2A. Numpy Array using arange()")

a = np.arange(10)
print(a)
type(a)

2A. Numpy Array using arange()
[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

In [20]:
#Method-2 by providing start, end

b =np.arange(0,10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [35]:
#Method-3 by providing start,end,step, data type

c =np.arange(0,10,2,int)
print(c)

[0 2 4 6 8]


In [26]:
#Try for floating numbers,
a = np.arange(0.1, 8.4, 0.7)
a

array([0.1, 0.8, 1.5, 2.2, 2.9, 3.6, 4.3, 5. , 5.7, 6.4, 7.1, 7.8])

In [4]:
#Try for floating numbers by giving dtype parameter
a = np.arange(0.6, 8.4, 0.7, int)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### 2B) np.linspace()

In [7]:
#linspace(start, stop, num=50)
#np.linspace() --> used when we want exact #of values between 2 numbers. ##no need to worry about step in this method

a = np.linspace(1,10)  #default #of values=50
a

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [18]:
a = np.linspace(0,21,4)
a

array([ 0.,  7., 14., 21.])

#### 2C) np.array()

In [31]:
#By using np.array() --> we can create multidimentional arrays in Numpy.
#Scalars are zero dimensional.

print("Example for 0-Dimensional numpy array\n")

a = np.array(40)
print("a : ", a)
print("Type of a:", type(a))
print("Dimentions of a: ", np.ndim(a))
print("Datatype of a: ", a.dtype)

Example for 0-Dimensional numpy array

a :  40
Type of a: <class 'numpy.ndarray'>
Dimentions of a:  0
Datatype of a:  int32


In [33]:
print("Example for 1-Dimensional numpy  array\n")

a = np.array(np.arange(0,5,0.5))
print("a : ", a)
print("Type of a:", type(a))
print("Dimentions of a: ", np.ndim(a))
print("Datatype of a: ", a.dtype)

Example for 1-Dimensional numpy  array

a :  [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
Type of a: <class 'numpy.ndarray'>
Dimentions of a:  1
Datatype of a:  float64


In [36]:
print("Example for 1-Dimensional numpy  array\n")

a = np.array([1,9,7,8,3,6,2,9,"H"])
print("a : ", a)
print("Type of a:", type(a))
print("Dimentions of a: ", np.ndim(a))
print("Datatype of a: ", a.dtype)

Example for 1-Dimensional numpy  array

a :  ['1' '9' '7' '8' '3' '6' '2' '9' 'H']
Type of a: <class 'numpy.ndarray'>
Dimentions of a:  1
Datatype of a:  <U11


` Hello `