# Numpy - Tutorials:

> - Numpy : Numerical Python <br>
> -  NumPy is the fundamental package for scientific computing in Python. <br>
> - It is a Python library that provides a multidimensional array object. <br>
> - NumPy arrays are faster and more compact than Python lists. <br>
> - While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous.

# 1. Import package

In [77]:
import numpy as np

# 2.Creating Numpy array:

### 2A) np.arange()

In [2]:
#arange([start,] stop[, step], [, dtype=None]
#np.arange() --> will be useful, when we know start, end, step size. But dont know howmany #of values will come

#Method-1: using np.arange()
print("2A. Numpy Array using arange()")

a = np.arange(10)
print(a)
type(a)

2A. Numpy Array using arange()
[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

In [3]:
#Method-2 by providing start, end

b =np.arange(0,10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
#Method-3 by providing start,end,step, data type

c =np.arange(0,10,2,int)
print(c)

[0 2 4 6 8]


In [5]:
#Try for floating numbers,
a = np.arange(0.1, 8.4, 0.7)
a

array([0.1, 0.8, 1.5, 2.2, 2.9, 3.6, 4.3, 5. , 5.7, 6.4, 7.1, 7.8])

In [6]:
#Try for floating numbers by giving dtype parameter
a = np.arange(0.6, 8.4, 0.7, int)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### 2B) np.linspace()

In [7]:
#linspace(start, stop, num=50)
#np.linspace() --> used when we want exact #of values between 2 numbers. ##no need to worry about step in this method

a = np.linspace(1,10)  #default #of values=50
a

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [8]:
a = np.linspace(0,21,4)
a

array([ 0.,  7., 14., 21.])

### 2C) np.array()

In [9]:
#By using np.array() --> we can create multidimentional arrays in Numpy.
#Scalars are zero dimensional.

print("Example for 0-Dimensional numpy array\n")

a = np.array(40)
print("array : ", a)
print("Type of a:", type(a))
print("Dimentions of a: ", np.ndim(a))
print("Datatype of a: ", a.dtype)

Example for 0-Dimensional numpy array

array :  40
Type of a: <class 'numpy.ndarray'>
Dimentions of a:  0
Datatype of a:  int32


In [10]:
print("Example for 1-Dimensional numpy  array\n")

a = np.array(np.arange(0,5,0.5))
print("array : ", a)
print("Type of a:", type(a))
print("Dimentions of a: ", np.ndim(a))
print("Datatype of a: ", a.dtype)

Example for 1-Dimensional numpy  array

array :  [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
Type of a: <class 'numpy.ndarray'>
Dimentions of a:  1
Datatype of a:  float64


In [11]:
print("Example for 1-Dimensional numpy  array\n")

a = np.array([1,9,7,8,3,6,2,9,'H'])
print("array : ", a)
print("Type of a:", type(a))
print("Dimentions of a: ", np.ndim(a))
print("Datatype of a: ", a.dtype)

Example for 1-Dimensional numpy  array

array :  ['1' '9' '7' '8' '3' '6' '2' '9' 'H']
Type of a: <class 'numpy.ndarray'>
Dimentions of a:  1
Datatype of a:  <U11


In [12]:
print("Example for 2-Dimensional numpy  array\n")

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("array : \n", a)
print("\nType of a:", type(a))
print("Dimentions of a: ", np.ndim(a))
print("Datatype of a: ", a.dtype)

Example for 2-Dimensional numpy  array

array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Type of a: <class 'numpy.ndarray'>
Dimentions of a:  2
Datatype of a:  int32


In [13]:
print("Example for 2-Dimensional numpy  array\n")

a = np.array(np.arange(20).reshape(4,5))
print("array : \n", a)
print("\nType of a:", type(a))
print("Dimentions of a: ", np.ndim(a))
print("Datatype of a: ", a.dtype)

Example for 2-Dimensional numpy  array

array : 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Type of a: <class 'numpy.ndarray'>
Dimentions of a:  2
Datatype of a:  int32


In [14]:
print("Example for 3-Dimensional numpy  array\n")

a = np.array(np.arange(20).reshape(2,2,5))
print("array : \n", a)
print("\nType of a:", type(a))
print("Dimentions of a: ", np.ndim(a))
print("Datatype of a: ", a.dtype)

Example for 3-Dimensional numpy  array

array : 
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]

Type of a: <class 'numpy.ndarray'>
Dimentions of a:  3
Datatype of a:  int32


In [15]:
print("Example for 3-Dimensional numpy  array\n")

a = np.array(np.arange(20).reshape(2,5,2))
print("array : \n", a)
print("\nType of a:", type(a))
print("Dimentions of a: ", np.ndim(a))
print("Datatype of a: ", a.dtype)

Example for 3-Dimensional numpy  array

array : 
 [[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]

Type of a: <class 'numpy.ndarray'>
Dimentions of a:  3
Datatype of a:  int32


# 3) ReShape the array

In [16]:
#The reshape() function is used to give a new shape to an array without changing its data
print("Example for 2-Dimensional numpy array with reshape\n")
print("reshape(#rows, #columns) = reshape(5,4)")

a = np.array(np.arange(20).reshape(5,4))
print("array : \n", a)
print("\nType of a:", type(a))
print("Dimentions of a: ", np.ndim(a))
print("Datatype of a: ", a.dtype)

Example for 2-Dimensional numpy array with reshape

reshape(#rows, #columns) = reshape(5,4)
array : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

Type of a: <class 'numpy.ndarray'>
Dimentions of a:  2
Datatype of a:  int32


In [17]:
print("Example for 2-Dimensional numpy array with reshape\n")
print("reshape(#rows, #columns) = reshape(4,5)")

a = np.array(np.arange(20).reshape(4,5))
print("array : \n", a)
print("\nType of a:", type(a))
print("Dimentions of a: ", np.ndim(a))
print("Datatype of a: ", a.dtype)

Example for 2-Dimensional numpy array with reshape

reshape(#rows, #columns) = reshape(4,5)
array : 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Type of a: <class 'numpy.ndarray'>
Dimentions of a:  2
Datatype of a:  int32


In [18]:
print("Example for 3-Dimensional numpy array with reshape\n")
print("reshape(#sets, #rows_in_each_set, #columns_in_each_set) = reshape(2,4,5)")

a = np.array(np.arange(40).reshape(2,4,5))
print("array : \n", a)
print("\nType of a:", type(a))
print("Dimentions of a: ", np.ndim(a))
print("Datatype of a: ", a.dtype)

Example for 3-Dimensional numpy array with reshape

reshape(#sets, #rows_in_each_set, #columns_in_each_set) = reshape(2,4,5)
array : 
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]]

Type of a: <class 'numpy.ndarray'>
Dimentions of a:  3
Datatype of a:  int32


# 4) Shape of Array

In [35]:
#shape--> returns share of the array

print("Example of Shape function for 0-Dimensional array:\n")
a = np.array(20)
print("array: \n", a)
print("\nShape: ", np.shape(a)) #approach1

print("\nShape: ", a.shape)#approach2
print("\n# of Dimensions", np.ndim(a))


Example of Shape function for 0-Dimensional array:

array: 
 20

Shape:  ()

Shape:  ()

# of Dimensions 0


In [36]:
print("Example of Shape function for 1-Dimensional array:\n")
a = np.array(np.arange(10))
print("array: \n", a)
print("\nShape: ", np.shape(a)) #approach1

print("\nShape: ", a.shape)#approach2
print("\n# of Dimensions", np.ndim(a))


Example of Shape function for 1-Dimensional array:

array: 
 [0 1 2 3 4 5 6 7 8 9]

Shape:  (10,)

Shape:  (10,)

# of Dimensions 1


In [38]:
print("Example of Shape function for 2-Dimensional array:\n")
a = np.array(np.arange(10).reshape(2,5))
print("array: \n", a)
print("\nShape: ", np.shape(a)) #approach1

print("\nShape: ", a.shape)#approach2
print("\n# of Dimensions", np.ndim(a))


Example of Shape function for 2-Dimensional array:

array: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]

Shape:  (2, 5)

Shape:  (2, 5)

# of Dimensions 2


In [40]:
print("Example of Shape function for 3-Dimensional array:\n")
a = np.array(np.arange(20).reshape(2,5,2))
print("array: \n", a)
print("\nShape: ", np.shape(a)) #approach1

print("\nShape: ", a.shape)#approach2
print("\n# of Dimensions", np.ndim(a))


Example of Shape function for 3-Dimensional array:

array: 
 [[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]

Shape:  (2, 5, 2)

Shape:  (2, 5, 2)

# of Dimensions 3


In [72]:
print("Example of Shape function for 2-Dimensional array and reassign the shape of array:\n")
a = np.array(np.arange(20).reshape(4,5))
print("array: \n", a)
print("\nShape: ", np.shape(a)) #approach1

print("\nShape: ", a.shape)#approach2
print("\n# of Dimensions", np.ndim(a))

print("\nRe assign the shape of array to 2,10\n")
a.shape = (2,10)
print("array: \n", a)


Example of Shape function for 2-Dimensional array and reassign the shape of array:

array: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Shape:  (4, 5)

Shape:  (4, 5)

# of Dimensions 2

Re assign the shape of array to 2,10

array: 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


# 5) Indexing and Slicing

In [57]:
#By using index we can access the elements in a Numpy array just like accessing elements in List, Tuple
#A[start:stop:step] this conecpt applicable to slicing the Numpy array aswell
print("Indexing Example for 1D array")
a = np.array([0,1,2,3,4,5,6,7])

print("\n Array:", a)
print("\n Access 3rd elements in Array: ", a[2])
print("\n Access first elements in Array: ", a[0])
print("\n Access last elements in Array: ", a[-1])

Indexing Example for 1D array

 Array: [0 1 2 3 4 5 6 7]

 Access 3rd elements in Array:  2

 Access first elements in Array:  0

 Access last elements in Array:  7


In [56]:
print("Indexing Example for 3D array")
a = np.array(np.arange(20).reshape(4,5))

print("\n Array:\n", a)
print("\n Access 1st row in Array: ", a[0])
print("\n Access last row in Array: ", a[-1])
print("\n Access first column in Array: ", a[:,0])
print("\n Access last column in Array: ", a[:,-1])

Indexing Example for 3D array

 Array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

 Access 1st row in Array:  [0 1 2 3 4]

 Access last row in Array:  [15 16 17 18 19]

 Access first column in Array:  [ 0  5 10 15]

 Access last column in Array:  [ 4  9 14 19]


In [58]:
print("Slicing Example for 3D array")
a = np.array(np.arange(20).reshape(4,5))

print("\n Array:\n", a)
print("\n Access middle array by eliminating borders:\n ", a[1:3,1:4])


Slicing Example for 3D array

 Array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

 Access middle array by eliminating borders:
  [[ 6  7  8]
 [11 12 13]]


In [2]:
print("Slicing Example for 2D array with 3 parameters.A[start:stop:step]")
a = np.array(np.arange(40).reshape(8,5))

print("\n Array:\n", a)
print("\n Access array with 3 parameters A[start:stop:step]:\n ", a[1:6:2])


Slicing Example for 2D array with 3 parameters.A[start:stop:step]

 Array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]

 Access array with 3 parameters A[start:stop:step]:
  [[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]]


# 6) Numpy Special Arrays: 
# ones(), ones_like(), zeros(), zeros_like(), empty(), transpose()

### np.ones()

In [10]:
#np.ones()--> is used to fill all ones in array with given shape.
#bydefault it will be float type

print("Ones() Example: with float type.\n")
a = np.ones(5)
print("Array:\n",a)
print("\nArray Dimension:", a.ndim)

Ones() Example: with float type.

Array:
 [1. 1. 1. 1. 1.]

Array Dimension: 1


In [13]:
print("Ones() Example: with defined type.\n")

a = np.ones(5, dtype=int)
print("Array:\n",a)
print("\nArray Dimension:", a.ndim)

Ones() Example: with float type.

Array:
 [1 1 1 1 1]

Array Dimension: 1


In [15]:
print("Ones() Example: with defined type and 2D array.\n")

a = np.ones((4,5), dtype=int)
print("Array:\n",a)
print("\nArray Dimension:", a.ndim)

Ones() Example: with defined type and 2D array.

Array:
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

Array Dimension: 2


In [19]:
print("Ones() Example: with defined type and 3D array.\n")

a = np.ones((3,4,5), dtype=int)
print("Array:\n",a)
print("\nArray Dimension:", a.ndim)

Ones() Example: with defined type and 3D array.

Array:
 [[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]

Array Dimension: 3


### np.ones_like()

In [18]:
#ones_like(<other_array_name>)--> used to print ones array in given ohter array dimension
example_array = np.array([8,4,5,6,3])
target_array = np.ones_like(example_array)
print("Example Array:\n",example_array)
print("\nTarget Array:\n",target_array)

Example Array:
 [8 4 5 6 3]

Target Array:
 [1 1 1 1 1]


In [21]:
example_array = np.arange(40).reshape(2,4,5)
target_array = np.ones_like(example_array)
print("Example Array:\n",example_array)
print("\nTarget Array:\n",target_array)

Example Array:
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]]

Target Array:
 [[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


### np.zeros()

In [23]:
#np.zeros()--> is used to fill all zeros in array with given shape.
#bydefault it will be float type

print("Zeros() Example: with defined type and 1D array.\n")

a = np.zeros(5, dtype=int)
print("Array:\n",a)
print("\nArray Dimension:", a.ndim)

Zeros() Example: with defined type and 1D array.

Array:
 [0 0 0 0 0]

Array Dimension: 1


In [24]:
print("Zeros() Example: with defined type and 2D array.\n")

a = np.zeros((4,5), dtype=int)
print("Array:\n",a)
print("\nArray Dimension:", a.ndim)

Zeros() Example: with defined type and 2D array.

Array:
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

Array Dimension: 2


In [25]:
print("Zeros() Example: with defined type and 3D array.\n")

a = np.zeros((3,4,5), dtype=int)
print("Array:\n",a)
print("\nArray Dimension:", a.ndim)

Zeros() Example: with defined type and 3D array.

Array:
 [[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]

Array Dimension: 3


### np.zeros_like()

In [26]:
example_array = np.arange(40).reshape(2,4,5)
target_array = np.zeros_like(example_array)
print("Example Array:\n",example_array)
print("\nTarget Array:\n",target_array)

Example Array:
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]]

Target Array:
 [[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


### np.empty()

In [33]:
#np.empty()--> usually entries are zeros, but they are arbitrary values.
a = np.empty((3,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### np.transpose()

In [46]:
#np.transpose() --> will convert rows into columns and columns into rows
print("Examp[le for Transpose function")

a = np.array(np.arange(12).reshape(3,4))
print("\nArray A:\n",a)
print("Shape of A:",a.shape)

#b = a.transpose()  --> #same as below
b = np.transpose(a)
print("\nTransposed Array B:\n",b)
print("Shape of B:",b.shape)

Examp[le for Transpose function

Array A:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape of A: (3, 4)

Transposed Array B:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Shape of B: (4, 3)


In [56]:
print("Example for Transpose function")

a = np.array(np.arange(3))
print("\nArray A:\n",a)
print("Shape of A:",a.shape)

#b = a.transpose()  --> #same as below
b = np.transpose(a)
print("\nTransposed Array B:\n",b)
print("Shape of B:",b.shape)


print("\n\n##################################################\n")
print("So 1-D arrays transpose will not be applicable ###Solution: -->use np.newaxis")
 
a = np.array(np.arange(3))
print("\nArray A:\n",a)
print("Shape of A:",a.shape)

b = a[:, np.newaxis]
print("\nTransposed Array B:\n",b)
print("Shape of B:",b.shape)

Example for Transpose function

Array A:
 [0 1 2]
Shape of A: (3,)

Transposed Array B:
 [0 1 2]
Shape of B: (3,)


##################################################

So 1-D arrays transpose will not be applicable ###Solution: -->use np.newaxis

Array A:
 [0 1 2]
Shape of A: (3,)

Transposed Array B:
 [[0]
 [1]
 [2]]
Shape of B: (3, 1)


# 7) Identity Array: np.identity(), np.eye()

### np.identity()

In [35]:
#np.identity(n, dtype=None)
#In linear algebra, the identity matrix or unit matrix, of size n is the n × n square matrix.
#values with ones on the main diagonal and zeros elsewhere.

print("Example of Identity Array 4X4\n")
a = np.identity(4)
a

Example of Identity Array



array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
print("Example of Identity Array 5X5, with Int type\n")
a = np.identity(5, int)
a

Example of Identity Array 5X5, with Int type



array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

### np.eye()

In [42]:
#np.eye(N,M,K=0, dtype=None)
#In linear algebra, the identity matrix or unit matrix, of size N X M  matrix.
#values with ones on the main diagonal and zeros elsewhere, but diagonal will starts at K ht position.

print("Example of Eye Array 4X4 . If we give single parameter it will become square matrix\n")
a = np.eye(4, dtype=int)
a

Example of Eye Array 4X4 . If we give single parameter it will become square matrix



array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [47]:
# rows X columns 

print("Eye(rows, columns) ecample. We have given rows X columns size. 4X6 Matrix")
a = np.eye(4,6, dtype=int)
a

Eye(rows, columns) ecample. We have given rows X columns size. 4X6 Matrix


array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0]])

In [59]:
# rows X columns with diagonal value position its K

print("Eye(rows, columns) ecample. We have given rows X columns size. 4X6 Matrix")
a = np.eye(4,6, dtype=int)
print("\nwithout K value:Array:\n",a)


print("\n\nEye(rows, columns, position_of_identiy_value) ecample. We have given rows X columns size.\
\n4X6 Matrix, identity starts at 2nd position")
a = np.eye(4,6,k=2, dtype=int)
a

Eye(rows, columns) ecample. We have given rows X columns size. 4X6 Matrix

without K value:Array:
 [[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]]


Eye(rows, columns, position_of_identiy_value) ecample. We have given rows X columns size.
4X6 Matrix, identity starts at 2nd position


array([[0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

# 8) Copies and Views 

### Case1:simple assignment. B = A

In [6]:
#When operating and manipulating arrays, their data is sometimes copied into a new array and sometimes not.
#Simple assignments make no copy of objects or their data.

print("Simple assignments make no copy of objects or their data.\n")

a = np.array(np.arange(12).reshape(3,4))
print("Given Array A:\n",a)

#Assign array A to B:
b = a
print("\nassigning B = A")
print("\n\nAssigned Array B:\n",b)

#check their ID's
print("\n\nID's: \n\tA id = ",id(a),"\n\tB id = ", id(b))

#check with is cluase:
print("\nB IS A :", b is a)

print("\nSO, simple assignment will not copy a new array")

#lets test:
print("\n\nModifiy value in b[1][1]=999")
b[1][1]=999
print("\nGiven Array A:\n",a)
print("\n\nAssigned Array B:\n",b)

Simple assignments make no copy of objects or their data.

Given Array A:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

assigning B = A


Assigned Array B:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


ID's: 
	A id =  1960538728048 
	B id =  1960538728048

B IS A : True

SO, simple assignment will not copy a new array


Modifiy value in b[1][1]=999

Given Array A:
 [[  0   1   2   3]
 [  4 999   6   7]
 [  8   9  10  11]]


Assigned Array B:
 [[  0   1   2   3]
 [  4 999   6   7]
 [  8   9  10  11]]


### Case2: view() --> Shallow Copy

In [120]:
#view()--> will create a new array, 
#But if we assing new values, our old reference also get reflected. 
#still we cannot change the shape of the array
#base is same.


print("Initial Arrays:b = a.view():#################################\n")
a = np.array(np.arange(20).reshape(4,5))
print("Array A\n",a)

b = a.view()
print("\nArray B\n",b)
print("\nID's: \n\tA id = ",id(a),"\n\tB id = ", id(b))
print("B is A: ", b is a)
print("B.base is A: ", b.base is a)


print("\n\nChanging shapes:b.shape = (2,10):#################################")
#change the shape of b
b.shape = (2,10)
print("\nArray A\n",a)
print("\nArray B\n",b)
print("\nID's: \n\tA id = ",id(a),"\n\tB id = ", id(b))
print("B is A: ", b is a)
print("B.base is A: ", b.base is a)


print("\n\nChanging values:b[0][0] = 999:#################################")
#change the value in b
b[0][0] = 999
print("\nArray A\n",a)
print("\nArray B\n",b)
print("\nID's: \n\tA id = ",id(a),"\n\tB id = ", id(b))
print("B is A: ", b is a)
print("B.base is A: ", b.base is a)


Initial Arrays:b = a.view():#################################

Array A
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Array B
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

ID's: 
	A id =  2055081117376 
	B id =  2055081117616
B is A:  False
B.base is A:  True


Changing shapes:b.shape = (2,10):#################################

Array A
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Array B
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]

ID's: 
	A id =  2055081117376 
	B id =  2055081117616
B is A:  False
B.base is A:  True


Changing values:b[0][0] = 999:#################################

Array A
 [[999   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]

Array B
 [[999   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]]

ID's: 
	A id =  2055081117376 
	B id =  2055081117616
B is A:  False
B.base is A:  True


### Case3: copy()--> DeepCopy

In [126]:
#copy()--> will create a complete new array, 
#base is not same.
#if we change the values in copied one, original will remain same


print("Initial Arrays:b = a.copy():#################################\n")
a = np.array(np.arange(20).reshape(4,5))
print("Array A\n",a)

b = a.copy()
print("\nArray B\n",b)
print("\nID's: \n\tA id = ",id(a),"\n\tB id = ", id(b))
print("B is A: ", b is a)
print("B.base is A: ", b.base is a)


print("\n\nChanging shapes:b.shape = (2,10):#################################")
#change the shape of b
b.shape = (2,10)
print("\nArray A\n",a)
print("\nArray B\n",b)
print("\nID's: \n\tA id = ",id(a),"\n\tB id = ", id(b))
print("B is A: ", b is a)
print("B.base is A: ", b.base is a)


print("\n\nChanging values:b[0][0] = 999:#################################")
#change the value in b
b[0][0] = 999
print("\nArray A\n",a)
print("\nArray B\n",b)
print("\nID's: \n\tA id = ",id(a),"\n\tB id = ", id(b))
print("B is A: ", b is a)
print("B.base is A: ", b.base is a)


Initial Arrays:b = a.copy():#################################

Array A
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Array B
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

ID's: 
	A id =  2055081118816 
	B id =  2055081119376
B is A:  False
B.base is A:  False


Changing shapes:b.shape = (2,10):#################################

Array A
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Array B
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]

ID's: 
	A id =  2055081118816 
	B id =  2055081119376
B is A:  False
B.base is A:  False


Changing values:b[0][0] = 999:#################################

Array A
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Array B
 [[999   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]]

ID's: 
	A id =  2055081118816 
	B id =  2055081119376
B is A:  False
B.base is A:  False


# 9) Boolean Indexing

In [135]:
#boolean indexing will be applied on top of numpy array and compared each value in array
#it is also possible to check on "<", "<=", ">" and ">=".

print("Example of Boolean indexing of Numpy Array")

a = np.array(np.arange(40,60).reshape(4,5))
print("Array:\n",a)

#check if given value is even or odd
print("check if given value is even or odd:\n")
print(a%2==0)

Example of Boolean indexing of Numpy Array
Array:
 [[40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]
check if given value is even or odd:

[[ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]]


In [140]:
print("Example of Boolean indexing of Numpy Array")

a = np.array(np.arange(40,60).reshape(4,5))
print("Array:\n",a)

#check if given value is <=47
print("\n\ncheck if given value is <=47:")
b = a<=47
b.astype(int)

Example of Boolean indexing of Numpy Array
Array:
 [[40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]


check if given value is <=47:


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# 10) Numerical Operations on Numpy Arrays

### Case1: Array with any value

In [9]:
#we can do arithmetic operations with scalars on top of numpy arrays
# +, -, *, **, /

print("Example for Adding number to array\n")

a = np.array(np.arange(40,60).reshape(4,5))
print("Array:\n",a)

print("\n\nArray+10:\n",a+10)

Example for Adding number to array

Array:
 [[40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]


Array+10:
 [[50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]]


In [8]:
a = np.array(np.arange(40,60).reshape(4,5))
print("Array:\n",a)

print("\n\nArray * 10:\n",a*10)

Array:
 [[40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]


Array * 10:
 [[400 410 420 430 440]
 [450 460 470 480 490]
 [500 510 520 530 540]
 [550 560 570 580 590]]


### Case2: Array with Array

In [153]:
#we can use  +, -, *, **, /
#Add 2 arrays 
print("Example for adding 2 arrays")
a = np.array(np.arange(20).reshape(4,5))
print("Array A:\n",a)

b = np.array(np.arange(60,80).reshape(4,5))
print("\n\nArray B:\n",b)

print("\n\nA + B:\n", a + b)

Example for adding 2 arrays
Array A:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


Array B:
 [[60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]]


A + B:
 [[60 62 64 66 68]
 [70 72 74 76 78]
 [80 82 84 86 88]
 [90 92 94 96 98]]


In [155]:
#multiple 2 arrays 
print("Example for multipling 2 arrays")
a = np.array(np.arange(20).reshape(4,5))
print("Array A:\n",a)

b = np.array(np.arange(40,60).reshape(4,5))
print("\n\nArray B:\n",b)

print("\n\nA * B:\n", a * b)

Example for multipling 2 arrays
Array A:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


Array B:
 [[40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]


A * B:
 [[   0   41   84  129  176]
 [ 225  276  329  384  441]
 [ 500  561  624  689  756]
 [ 825  896  969 1044 1121]]


### Case3: Matrix Multiplication

In [162]:
print("Example for matrix multipling 2 arrays with dot()")
a = np.array(np.arange(6).reshape(2,3))
print("Array A:\n",a)

b= np.array(np.arange(6).reshape(3,2))
print("\nArray B:\n",b)

print("\nMatrix Multiplication = np.dot(A,B):\n", np.dot(a, b))

Example for matrix multipling 2 arrays with dot()
Array A:
 [[0 1 2]
 [3 4 5]]

Array B:
 [[0 1]
 [2 3]
 [4 5]]

Matrix Multiplication = np.dot(A,B):
 [[10 13]
 [28 40]]


# 11) Matrices vs. Two-Dimensional Arrays

In [167]:
#two-dimensional numpy arrays can be considered as matrices. #but they are different
#Matrix in Numpy are subset of two-dimensional arrays.
#We can convert a two-dimensional array into a matrix by applying the "mat" function.

print("Example to convert Numpy 2D array into Numpy Matrix")
a = np.array(np.arange(6).reshape(2,3))
print("Array A:\n",a)
print("\nType of A: ",type(a))

print("\n\nConvert 2D array to Matrix: np.mat(array)")
MatA = np.mat(a)
print("Matrix MatA:\n",MatA)
print("\nType of MatA: ",type(MatA))

Example to convert Numpy 2D array into Numpy Matrix
Array A:
 [[0 1 2]
 [3 4 5]]

Type of A:  <class 'numpy.ndarray'>


Convert 2D array to Matrix: np.mat(array)
Matrix MatA:
 [[0 1 2]
 [3 4 5]]

Type of MatA:  <class 'numpy.matrixlib.defmatrix.matrix'>


# 12) Broadcasting

In [27]:
"""
1). Braodcasting allows to perform arithmetic operations on arrays of different shapes.
2). In 2 different shapes of arrays, we are transforming smaller array shape into larger array shape 
    and then perform given operataions
3). In 2nd point the smaller array is "broadcasted" 
4). For Broadcasting we wont use any additional keyword, bydefault smaller array will converted into bigger array shape
"""

print("Broading Example:")
a = np.array(np.arange(12).reshape(3,4))
print("\nArray A: \n", a)

b = np.array(np.arange(4))
print("\nArray B: \n", b)

print("\nLet's see how array B converted into given Bigger array shape:")
#print("\n", b,"\n", b,"\n", b)
#c = np.array([b,b,b])
c = np.array([b,]*3)
print(c)

print("\nAddition of A, B:\n",a + b)


Broading Example:

Array A: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Array B: 
 [0 1 2 3]

Let's see how array B converted into given Bigger array shape:
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]

Addition of A, B:
 [[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]]


In [33]:
print("Different ways to repliocate numpy array ")
x = np.array([1,2,3])
y = np.array([x,x,x])
z = np.array([x]*3)
z1 = np.array([x,]*3)

print("Array X:\n",x)
print("\nArray Y:\n",y)
print("\nArray Z:\n",z)
print("\nArray Z1:\n",z1)

Different ways to repliocate numpy array 
Array X:
 [1 2 3]

Array Y:
 [[1 2 3]
 [1 2 3]
 [1 2 3]]

Array Z:
 [[1 2 3]
 [1 2 3]
 [1 2 3]]

Array Z1:
 [[1 2 3]
 [1 2 3]
 [1 2 3]]


# 13) Numpy array functions:

### max(), min(), avg(), sum(), size() 

In [69]:
a = np.array(np.arange(6).reshape(2,3))
print("Array A:\n",a)

print("\nMamimum value in A: ", np.max(a))
print("Mamimum value in A: ", a.max())

print("\nMinimum value in A: ", np.min(a))
print("Minimum value in A: ", a.min())

print("\nAverage value in A: ", np.mean(a))
print("Average value in A: ", a.mean())

print("\nSum value in A: ", np.sum(a))
print("Sum value in A: ", a.sum())

print("\nSize of A: ", np.size(a))


Array A:
 [[0 1 2]
 [3 4 5]]

Mamimum value in A:  5
Mamimum value in A:  5

Minimum value in A:  0
Minimum value in A:  0

Average value in A:  2.5
Average value in A:  2.5

Sum value in A:  15
Sum value in A:  15

Size of A:  6


### sin(), cos(), exp(), log(), ..................Mathematical functions

In [76]:
a = np.array(np.arange(6).reshape(2,3))
print("Array A:\n",a)

print("\nApply Sin() function to Array A:\n",np.sin(a))

print("\nApply Cos() function to Array A:\n",np.cos(a))

print("\nApply exp() function to Array A:\n",np.exp(a))

print("\nApply log() function to Array A:\n",np.log(a))



Array A:
 [[0 1 2]
 [3 4 5]]

Apply Sin() function to Array A:
 [[ 0.          0.84147098  0.90929743]
 [ 0.14112001 -0.7568025  -0.95892427]]

Apply Cos() function to Array A:
 [[ 1.          0.54030231 -0.41614684]
 [-0.9899925  -0.65364362  0.28366219]]

Apply exp() function to Array A:
 [[  1.           2.71828183   7.3890561 ]
 [ 20.08553692  54.59815003 148.4131591 ]]

Apply log() function to Array A:
 [[      -inf 0.         0.69314718]
 [1.09861229 1.38629436 1.60943791]]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: RuntimeWarning: divide by zero encountered in log
  # Remove the CWD from sys.path while we load stuff.
