# Numpy - Tutorials:

> - Numpy : Numerical Python <br>
> -  NumPy is the fundamental package for scientific computing in Python. <br>
> - It is a Python library that provides a multidimensional array object. 

# 1. Import package

In [1]:
import numpy as np

# 2.Creating Numpy array:

#### 2A) np.arange()

In [2]:
#arange([start,] stop[, step], [, dtype=None]
#np.arange() --> will be useful, when we know start, end, step size. But dont know howmany #of values will come

#Method-1: using np.arange()
print("2A. Numpy Array using arange()")

a = np.arange(10)
print(a)
type(a)

2A. Numpy Array using arange()
[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

In [3]:
#Method-2 by providing start, end

b =np.arange(0,10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
#Method-3 by providing start,end,step, data type

c =np.arange(0,10,2,int)
print(c)

[0 2 4 6 8]


In [5]:
#Try for floating numbers,
a = np.arange(0.1, 8.4, 0.7)
a

array([0.1, 0.8, 1.5, 2.2, 2.9, 3.6, 4.3, 5. , 5.7, 6.4, 7.1, 7.8])

In [6]:
#Try for floating numbers by giving dtype parameter
a = np.arange(0.6, 8.4, 0.7, int)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### 2B) np.linspace()

In [7]:
#linspace(start, stop, num=50)
#np.linspace() --> used when we want exact #of values between 2 numbers. ##no need to worry about step in this method

a = np.linspace(1,10)  #default #of values=50
a

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [8]:
a = np.linspace(0,21,4)
a

array([ 0.,  7., 14., 21.])

#### 2C) np.array()

In [9]:
#By using np.array() --> we can create multidimentional arrays in Numpy.
#Scalars are zero dimensional.

print("Example for 0-Dimensional numpy array\n")

a = np.array(40)
print("array : ", a)
print("Type of a:", type(a))
print("Dimentions of a: ", np.ndim(a))
print("Datatype of a: ", a.dtype)

Example for 0-Dimensional numpy array

array :  40
Type of a: <class 'numpy.ndarray'>
Dimentions of a:  0
Datatype of a:  int32


In [10]:
print("Example for 1-Dimensional numpy  array\n")

a = np.array(np.arange(0,5,0.5))
print("array : ", a)
print("Type of a:", type(a))
print("Dimentions of a: ", np.ndim(a))
print("Datatype of a: ", a.dtype)

Example for 1-Dimensional numpy  array

array :  [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
Type of a: <class 'numpy.ndarray'>
Dimentions of a:  1
Datatype of a:  float64


In [11]:
print("Example for 1-Dimensional numpy  array\n")

a = np.array([1,9,7,8,3,6,2,9,'H'])
print("array : ", a)
print("Type of a:", type(a))
print("Dimentions of a: ", np.ndim(a))
print("Datatype of a: ", a.dtype)

Example for 1-Dimensional numpy  array

array :  ['1' '9' '7' '8' '3' '6' '2' '9' 'H']
Type of a: <class 'numpy.ndarray'>
Dimentions of a:  1
Datatype of a:  <U11


In [12]:
print("Example for 2-Dimensional numpy  array\n")

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("array : \n", a)
print("\nType of a:", type(a))
print("Dimentions of a: ", np.ndim(a))
print("Datatype of a: ", a.dtype)

Example for 2-Dimensional numpy  array

array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Type of a: <class 'numpy.ndarray'>
Dimentions of a:  2
Datatype of a:  int32


In [13]:
print("Example for 2-Dimensional numpy  array\n")

a = np.array(np.arange(20).reshape(4,5))
print("array : \n", a)
print("\nType of a:", type(a))
print("Dimentions of a: ", np.ndim(a))
print("Datatype of a: ", a.dtype)

Example for 2-Dimensional numpy  array

array : 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Type of a: <class 'numpy.ndarray'>
Dimentions of a:  2
Datatype of a:  int32


In [14]:
print("Example for 3-Dimensional numpy  array\n")

a = np.array(np.arange(20).reshape(2,2,5))
print("array : \n", a)
print("\nType of a:", type(a))
print("Dimentions of a: ", np.ndim(a))
print("Datatype of a: ", a.dtype)

Example for 3-Dimensional numpy  array

array : 
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]

Type of a: <class 'numpy.ndarray'>
Dimentions of a:  3
Datatype of a:  int32


In [15]:
print("Example for 3-Dimensional numpy  array\n")

a = np.array(np.arange(20).reshape(2,5,2))
print("array : \n", a)
print("\nType of a:", type(a))
print("Dimentions of a: ", np.ndim(a))
print("Datatype of a: ", a.dtype)

Example for 3-Dimensional numpy  array

array : 
 [[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]

Type of a: <class 'numpy.ndarray'>
Dimentions of a:  3
Datatype of a:  int32


# 3) ReShape the array

In [16]:
#The reshape() function is used to give a new shape to an array without changing its data
print("Example for 2-Dimensional numpy array with reshape\n")
print("reshape(#rows, #columns) = reshape(5,4)")

a = np.array(np.arange(20).reshape(5,4))
print("array : \n", a)
print("\nType of a:", type(a))
print("Dimentions of a: ", np.ndim(a))
print("Datatype of a: ", a.dtype)

Example for 2-Dimensional numpy array with reshape

reshape(#rows, #columns) = reshape(5,4)
array : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

Type of a: <class 'numpy.ndarray'>
Dimentions of a:  2
Datatype of a:  int32


In [17]:
print("Example for 2-Dimensional numpy array with reshape\n")
print("reshape(#rows, #columns) = reshape(4,5)")

a = np.array(np.arange(20).reshape(4,5))
print("array : \n", a)
print("\nType of a:", type(a))
print("Dimentions of a: ", np.ndim(a))
print("Datatype of a: ", a.dtype)

Example for 2-Dimensional numpy array with reshape

reshape(#rows, #columns) = reshape(4,5)
array : 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Type of a: <class 'numpy.ndarray'>
Dimentions of a:  2
Datatype of a:  int32


In [18]:
print("Example for 3-Dimensional numpy array with reshape\n")
print("reshape(#sets, #rows_in_each_set, #columns_in_each_set) = reshape(2,4,5)")

a = np.array(np.arange(40).reshape(2,4,5))
print("array : \n", a)
print("\nType of a:", type(a))
print("Dimentions of a: ", np.ndim(a))
print("Datatype of a: ", a.dtype)

Example for 3-Dimensional numpy array with reshape

reshape(#sets, #rows_in_each_set, #columns_in_each_set) = reshape(2,4,5)
array : 
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]]

Type of a: <class 'numpy.ndarray'>
Dimentions of a:  3
Datatype of a:  int32


# 4) Shape of Array

In [35]:
#shape--> returns share of the array

print("Example of Shape function for 0-Dimensional array:\n")
a = np.array(20)
print("array: \n", a)
print("\nShape: ", np.shape(a)) #approach1

print("\nShape: ", a.shape)#approach2
print("\n# of Dimensions", np.ndim(a))


Example of Shape function for 0-Dimensional array:

array: 
 20

Shape:  ()

Shape:  ()

# of Dimensions 0


In [36]:
print("Example of Shape function for 1-Dimensional array:\n")
a = np.array(np.arange(10))
print("array: \n", a)
print("\nShape: ", np.shape(a)) #approach1

print("\nShape: ", a.shape)#approach2
print("\n# of Dimensions", np.ndim(a))


Example of Shape function for 1-Dimensional array:

array: 
 [0 1 2 3 4 5 6 7 8 9]

Shape:  (10,)

Shape:  (10,)

# of Dimensions 1


In [38]:
print("Example of Shape function for 2-Dimensional array:\n")
a = np.array(np.arange(10).reshape(2,5))
print("array: \n", a)
print("\nShape: ", np.shape(a)) #approach1

print("\nShape: ", a.shape)#approach2
print("\n# of Dimensions", np.ndim(a))


Example of Shape function for 2-Dimensional array:

array: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]

Shape:  (2, 5)

Shape:  (2, 5)

# of Dimensions 2


In [40]:
print("Example of Shape function for 3-Dimensional array:\n")
a = np.array(np.arange(20).reshape(2,5,2))
print("array: \n", a)
print("\nShape: ", np.shape(a)) #approach1

print("\nShape: ", a.shape)#approach2
print("\n# of Dimensions", np.ndim(a))


Example of Shape function for 3-Dimensional array:

array: 
 [[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]

Shape:  (2, 5, 2)

Shape:  (2, 5, 2)

# of Dimensions 3


` Hello `